services:
  # Service 1: The FastAPI Backend
  - type: web
    name: llm-backend
    runtime: docker
    repo: https://github.com/majisoumya/llm2.git # Change this!
    rootDir: ./backend
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /
    plan: free
    # This section tells Render to use the Environment Group you created
    envVarGroups:
      - name: llm-secrets # <-- Use the exact name from Step A

  # Service 2: The Streamlit Frontend
  - type: web
    name: llm-frontend
    runtime: docker
    repo: https://github.com/majisoumya/llm2.git # Change this!
    rootDir: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    envVars:
      - key: BACKEND_URL
        value: http://llm-backend:8000
