services:
  # Service 1: The FastAPI Backend
  # We have REMOVED the envVars section to guarantee deployment.
  - type: web
    name: llm-backend
    runtime: docker
    repo: https://github.com/majisoumya/llm2.git # Change this!
    rootDir: ./backend
    dockerfilePath: ./backend/dockerfile
    healthCheckPath: /
    plan: free

  # Service 2: The Streamlit Frontend
  - type: web
    name: llm-frontend
    runtime: docker
    repo: https://github.com/majisoumya/llm2.git # Change this!
    rootDir: ./frontend
    dockerfilePath: ./frontend/dockerfile
    plan: free
    envVars:
      - key: BACKEND_URL
        value: http://llm-backend:8000
