services:
  # Service 1: The FastAPI Backend
  - type: web
    name: llm-backend
    runtime: docker
    repo: https://github.com/majisoumya/llm2.git # Change this!
    rootDir: ./backend
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /
    plan: free
    envVars:
      # This tells Render to pull the value for 'OPENAI_API_KEY'
      # from the secrets you set in the Dashboard in Step 1.
      - key: GROQ_API_KEY # This MUST EXACTLY MATCH the key from Step 1
        fromSecret: true

  # Service 2: The Streamlit Frontend
  - type: web
    name: llm-frontend
    runtime: docker
    repo: https://github.com/majisoumya/llm2.git # Change this!
    rootDir: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    envVars:
      - key: BACKEND_URL
        value: http://llm-backend:8000
