services:
  # Service 1: The FastAPI Backend
  - type: web
    name: llm-backend
    runtime: docker
    repo: https://github.com/majisoumya/llm2.git # Change this!
    rootDir: ./backend
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /
    plan: free
    envVars:
      # This is an example of a secret key.
      # You must create a secret named 'YOUR_MODEL_API_KEY' in the Render Environment tab.
      - key: YOUR_MODEL_API_KEY
        fromSecret: true

  # Service 2: The Streamlit Frontend
  - type: web
    name: llm-frontend
    runtime: docker
    repo: https://github.com/majisoumya/llm2.git # Change this!
    rootDir: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    envVars:
      # This correctly points the frontend to the internal address of the backend
      - key: BACKEND_URL
        value: http://llm-backend:8000
