services:
  # Service 1: The FastAPI Backend
  - type: web
    name: llm-backend
    runtime: docker
    repo: https://github.com/majisoumya/llm2.gitE # Change this!
    rootDir: ./backend
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: / # A simple path to check if the service is up
    plan: free # Or a paid plan for more resources
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.19
      # Add any secret keys your model needs here (e.g., OPENAI_API_KEY)
      # Go to Render Dashboard -> Environment to set secret values
      - key: YOUR_MODEL_API_KEY
        fromSecret: true

  # Service 2: The Streamlit Frontend
  - type: web
    name: llm-frontend
    runtime: docker
    repo: https://github.com/majisoumya/llm2.git # Change this!
    rootDir: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    plan: free # Or a paid plan
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.19
      # This is the magic part! Render automatically injects the backend's URL
      - key: BACKEND_URL
        fromService:
          type: web
          name: llm-backend
          property: url
